target("AstOpt")
    set_kind("shared")
    add_files("**.cpp")
    -- add_files("**.c")
    add_headerfiles("**.hpp", {prefixdir="AstOpt"})
    add_headerfiles("**.h", {prefixdir="AstOpt"})
    add_defines("AST_BUILD_LIB_OPT")
    add_deps("AstCore", "AstUtil")
    -- add_extrafiles("xmake.lua")    
